using System;
using System.ComponentModel.DataAnnotations.Schema;
using NuGet.Versioning;

namespace AvantiPoint.Packages.Core;

/// <summary>
/// Read-only entity mapped to vw_PackageWithJsonData view.
/// Provides package data with JSON-formatted relationship data (Dependencies, PackageTypes, TargetFrameworks).
/// </summary>
[Table("vw_PackageWithJsonData")]
public class PackageWithJsonData
{
    public int Key { get; set; }
    public required string Id { get; set; }

    public NuGetVersion Version =>
        NuGetVersion.Parse(
            OriginalVersionString != null
                ? OriginalVersionString
                : NormalizedVersionString);

    // These are mapped to database columns
    public string NormalizedVersionString { get; set; } = string.Empty;
    public string? OriginalVersionString { get; set; }

    public string[]? Authors { get; set; }
    public string? Description { get; set; }
    public long Downloads { get; set; }
    public bool HasReadme { get; set; }
    public bool HasEmbeddedIcon { get; set; }
    public bool HasEmbeddedLicense { get; set; }
    public bool IsPrerelease { get; set; }
    public string? ReleaseNotes { get; set; }
    public string? Language { get; set; }
    public bool Listed { get; set; }
    public string? LicenseExpression { get; set; }
    public bool IsSigned { get; set; }
    public bool IsTool { get; set; }
    public bool IsDevelopmentDependency { get; set; }
    public string? MinClientVersion { get; set; }
    public DateTime Published { get; set; }
    public bool RequireLicenseAcceptance { get; set; }
    public SemVerLevel SemVerLevel { get; set; }
    public string? Summary { get; set; }
    public string? Title { get; set; }

    public Uri? IconUrl { get; set; }
    public Uri? LicenseUrl { get; set; }
    public Uri? ProjectUrl { get; set; }
    public Uri? RepositoryUrl { get; set; }

    public string? IconUrlString => IconUrl?.AbsoluteUri;
    public string? LicenseUrlString => LicenseUrl?.AbsoluteUri;
    public string? ProjectUrlString => ProjectUrl?.AbsoluteUri;
    public string? RepositoryUrlString => RepositoryUrl?.AbsoluteUri;

    public string? RepositoryType { get; set; }
    public string? RepositoryCommit { get; set; }
    public DateTime? RepositoryCommitDate { get; set; }
    public string[]? Tags { get; set; }

    // Deprecation properties
    public bool IsDeprecated { get; set; }
    public string[]? DeprecationReasons { get; set; }
    public string? DeprecationMessage { get; set; }
    public string? DeprecatedAlternatePackageId { get; set; }
    public string? DeprecatedAlternatePackageVersionRange { get; set; }

    public byte[]? RowVersion { get; set; }

    /// <summary>
    /// JSON string containing dependencies - dynamically generated by database view.
    /// </summary>
    public string? DependenciesJson { get; set; }

    /// <summary>
    /// JSON string containing package types - dynamically generated by database view.
    /// </summary>
    public string? PackageTypesJson { get; set; }

    /// <summary>
    /// JSON string containing target frameworks - dynamically generated by database view.
    /// </summary>
    public string? TargetFrameworksJson { get; set; }
}
