// <auto-generated />
using System;
using AvantiPoint.Packages.Host.Database.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvantiPoint.Packages.Host.Database.PostgreSql.Migrations
{
    [DbContext(typeof(HostPostgreSqlContext))]
    [Migration("20260702154540_AddPublishTargetProtocol")]
    partial class AddPublishTargetProtocol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostAccessSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("RequireNewUserApproval")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("HostAccessSettings", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystemToken")
                        .HasColumnType("boolean");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<int>("Scopes")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TokenPrefix");

                    b.HasIndex("UserEmail");

                    b.ToTable("HostApiTokens", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroup", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("HostPackageGroups", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroupMember", b =>
                {
                    b.Property<string>("PackageGroupName")
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.HasKey("PackageGroupName", "PackageId");

                    b.ToTable("HostPackageGroupMembers", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroupSyndication", b =>
                {
                    b.Property<string>("PackageGroupName")
                        .HasColumnType("text");

                    b.Property<string>("PublishTargetName")
                        .HasColumnType("text");

                    b.HasKey("PackageGroupName", "PublishTargetName");

                    b.HasIndex("PublishTargetName");

                    b.ToTable("HostPackageGroupSyndications", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPublishTarget", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Legacy")
                        .HasColumnType("boolean");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NuGet");

                    b.Property<string>("PublishEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("HostPublishTargets", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostTokenNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HostApiTokenId")
                        .HasColumnType("integer");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HostApiTokenId");

                    b.ToTable("HostTokenNotifications", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostUser", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("CanConsume")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPublish")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalSubjectId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("HostUsers", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostApiToken", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Host.Admin.Entities.HostUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroupMember", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroup", "PackageGroup")
                        .WithMany("Members")
                        .HasForeignKey("PackageGroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageGroup");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroupSyndication", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroup", "PackageGroup")
                        .WithMany("Syndications")
                        .HasForeignKey("PackageGroupName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvantiPoint.Packages.Host.Admin.Entities.HostPublishTarget", "PublishTarget")
                        .WithMany("Syndications")
                        .HasForeignKey("PublishTargetName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageGroup");

                    b.Navigation("PublishTarget");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostTokenNotification", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Host.Admin.Entities.HostApiToken", "Token")
                        .WithMany()
                        .HasForeignKey("HostApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPackageGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Syndications");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostPublishTarget", b =>
                {
                    b.Navigation("Syndications");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Host.Admin.Entities.HostUser", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
