namespace OpenFeed;

/// <summary>
/// Reference to the global Program class for use with WebApplicationFactory.
/// This allows tests to reference OpenFeed.Program while the actual entry point
/// remains in the global namespace (generated by top-level statements).
/// </summary>
public partial class Program
{
    // This class serves as a namespace wrapper for the global Program class
    // generated by top-level statements. WebApplicationFactory will use this
    // type to locate the assembly and entry point.
}

