<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3.runner.common" />
    <ProjectReference Include="../../src/AvantiPoint.Packages.Registry.Native/AvantiPoint.Packages.Registry.Native.csproj" />
    <ProjectReference Include="../../src/AvantiPoint.Packages.Database.Sqlite/AvantiPoint.Packages.Database.Sqlite.csproj" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /><None Update="Fixtures/*" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
