  
name: UITests

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - run: dotnet build APPackages.sln -c Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: NuGet Packages
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: Artifacts/

