  
name: Bulid Package Feed

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'theme/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/requirements.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'theme/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/requirements.txt'

jobs:

  build:
    name: Build Package Feed
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore APPackages.sln
        name: Restore NuGet Packages

      - run: dotnet build APPackages.sln -c Release --no-restore
        name: Build Solution

      - name: Upload NuGet Packages
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

      - name: Publish to In-House NuGet Feed
        if: ${{ github.event_name != 'pull_request' }}
        uses: dansiegel/publish-nuget@master
        with:
          filename: 'Artifacts/*.nupkg'
          feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
          apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

      - name: Publish to NuGet.org
        if: ${{ github.event_name != 'pull_request' }}
        uses: dansiegel/publish-nuget@master
        with:
          filename: 'Artifacts/*.nupkg'
          apiKey: ${{ secrets.NUGET_API_KEY }}

