  
name: Bulid Package Feed

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'theme/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/requirements.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'theme/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - '.github/workflows/requirements.txt'

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: Build Package Feed
      solution-path: APPackages.sln
      dotnet-version: 9.0.x
      code-sign: false
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  deploy-internal:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    if: ${{ github.event_name == 'push' }}
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  # deploy-public:
  #   uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
  #   needs: build
  #   if: ${{ github.event_name == 'push' }}
  #   with:
  #     name: Deploy Public
  #   secrets:
  #     apiKey: ${{ secrets.NUGET_API_KEY }}
