  
name: Bulid Package Feed

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build Package Feed
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest

      - run: nuget restore APPackages.sln

      - run: dotnet build APPackages.sln -c Release

      - name: NuGet Packages
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: NuGet
          path: Artifacts/

      - name: NuGet Publish
        if: ${{ github.event_name != 'pull_request' }}
        uses: dansiegel/publish-nuget@master
        with:
          filename: 'Artifacts/*.nupkg'
          repo-url: ${{ secrets.IN_HOUSE_NUGET_FEED }}
          api-key: ${{ secrets.IN_HOUSE_API_KEY }}

      - name: NuGet Publish
        if: ${{ github.event_name != 'pull_request' }}
        uses: dansiegel/publish-nuget@master
        with:
          filename: 'Artifacts/*.nupkg'
          api-key: ${{ secrets.NUGET_API_KEY }}

