// <auto-generated />
using System;
using AvantiPoint.Packages.Database.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvantiPoint.Packages.Database.Sqlite.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Npm.NpmDistTag", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("PackageKey");

                    b.HasIndex("FeedId", "PackageKey", "Tag")
                        .IsUnique();

                    b.ToTable("NpmDistTags");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Npm.NpmPackage", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("FeedId", "Name")
                        .IsUnique();

                    b.ToTable("NpmPackages");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Npm.NpmVersion", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Published");

                    b.Property<int>("PackageKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Published")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shasum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarballPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("PackageKey");

                    b.HasIndex("FeedId", "PackageKey", "Version")
                        .IsUnique();

                    b.ToTable("NpmVersions");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciBlob", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OciSegment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("FeedId", "OciSegment", "Digest")
                        .IsUnique();

                    b.ToTable("OciBlobs");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciManifest", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OciSegment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Published");

                    b.Property<string>("PlatformArch")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformOs")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("FeedId", "OciSegment", "Digest")
                        .IsUnique();

                    b.ToTable("OciManifests");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciRepository", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OciSegment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("FeedId", "OciSegment", "Name")
                        .IsUnique();

                    b.ToTable("OciRepositories");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciTag", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestDigest")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OciSegment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Published");

                    b.Property<int>("RepositoryKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("RepositoryKey");

                    b.HasIndex("FeedId", "OciSegment", "RepositoryKey", "Tag")
                        .IsUnique();

                    b.ToTable("OciTags");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciUpload", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OciSegment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UploadId")
                        .IsUnique();

                    b.ToTable("OciUploads");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Package", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecatedAlternatePackageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecatedAlternatePackageVersionRange")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecationMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecationReasons")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("default");

                    b.Property<bool>("HasEmbeddedIcon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEmbeddedLicense")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasReadme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<string>("IndexedWith")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDevelopmentDependency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrerelease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseExpression")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Listed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinClientVersion")
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedVersionString")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT COLLATE NOCASE")
                        .HasColumnName("Version");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Published");

                    b.Property<string>("OriginalVersionString")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("OriginalVersion");

                    b.Property<int?>("PackageSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Published")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ReleaseNotes");

                    b.Property<string>("RepositoryCommit")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RepositoryCommitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireLicenseAcceptance")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SemVerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Id");

                    b.HasIndex("Origin");

                    b.HasIndex("PackageSourceId");

                    b.HasIndex("FeedId", "Id");

                    b.HasIndex("Id", "IndexedWith");

                    b.HasIndex("FeedId", "Id", "NormalizedVersionString")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageDependency", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<int>("PackageKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFramework")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionRange")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Id");

                    b.HasIndex("PackageKey");

                    b.ToTable("PackageDependencies");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPlatform")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPlatformVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NuGetClient")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("NuGetClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgentString")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageKey");

                    b.ToTable("PackageDownloads");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CachingStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("MirrorSignaturePolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PackageSources");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageType", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<int>("PackageKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Name");

                    b.HasIndex("PackageKey");

                    b.ToTable("PackageTypes");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageVulnerability", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionRange")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("VulnerabilityKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("PackageId");

                    b.HasIndex("VulnerabilityKey");

                    b.HasIndex("PackageId", "VersionRange");

                    b.ToTable("PackageVulnerabilities");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageWithJsonData", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecatedAlternatePackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecatedAlternatePackageVersionRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecationMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeprecationReasons")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEmbeddedIcon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasEmbeddedLicense")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasReadme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDevelopmentDependency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrerelease")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseExpression")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Listed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinClientVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedVersionString")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Version");

                    b.Property<string>("OriginalVersionString")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("OriginalVersion");

                    b.Property<string>("PackageTypesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Published")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryCommit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RepositoryCommitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireLicenseAcceptance")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.Property<int>("SemVerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFrameworksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("vw_PackageWithJsonData");

                    b.ToView("vw_PackageWithJsonData", (string)null);
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.RepositorySigningCertificate", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstUsed")
                        .HasColumnType("TEXT");

                    b.Property<int>("HashAlgorithm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicCertificateBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("FirstUsed");

                    b.HasIndex("LastUsed");

                    b.HasIndex("Fingerprint", "HashAlgorithm")
                        .IsUnique();

                    b.HasIndex("IsActive", "NotBefore", "NotAfter");

                    b.ToTable("RepositorySigningCertificates");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.SearchIndexState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReconcileCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReconcileInProgress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SearchIndexStates");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.TargetFramework", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moniker")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.Property<int>("PackageKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("Moniker");

                    b.HasIndex("PackageKey");

                    b.ToTable("TargetFrameworks");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.VulnerabilityRecord", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvisoryUrl")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("AdvisoryUrl");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("VulnerabilityRecords");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Npm.NpmDistTag", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Entities.Npm.NpmPackage", "Package")
                        .WithMany("DistTags")
                        .HasForeignKey("PackageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Npm.NpmVersion", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Entities.Npm.NpmPackage", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciTag", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Entities.Oci.OciRepository", "Repository")
                        .WithMany("Tags")
                        .HasForeignKey("RepositoryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Package", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.PackageSource", "PackageSource")
                        .WithMany("Packages")
                        .HasForeignKey("PackageSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PackageSource");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageDependency", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Package", "Package")
                        .WithMany("Dependencies")
                        .HasForeignKey("PackageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageDownload", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Package", "Package")
                        .WithMany("PackageDownloads")
                        .HasForeignKey("PackageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageType", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Package", "Package")
                        .WithMany("PackageTypes")
                        .HasForeignKey("PackageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageVulnerability", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.VulnerabilityRecord", "Vulnerability")
                        .WithMany("AffectedPackages")
                        .HasForeignKey("VulnerabilityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.TargetFramework", b =>
                {
                    b.HasOne("AvantiPoint.Packages.Core.Package", "Package")
                        .WithMany("TargetFrameworks")
                        .HasForeignKey("PackageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Npm.NpmPackage", b =>
                {
                    b.Navigation("DistTags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Entities.Oci.OciRepository", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.Package", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("PackageDownloads");

                    b.Navigation("PackageTypes");

                    b.Navigation("TargetFrameworks");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.PackageSource", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("AvantiPoint.Packages.Core.VulnerabilityRecord", b =>
                {
                    b.Navigation("AffectedPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
